### ISSUE TITLE
New Handwriting

### ISSUE THREAD

**Issue by 1337w0rm** [SaiTeja69/Assignment_Writer#2]
I would like to add my own handwriting to this repo. Can you give some insight on how to do that ? I'm guessing that just changing the png images with my own with the same name would do the job. BTW really loved this idea. 

Thanks.

**Comment by SaiTeja69** [comment]
Create a new folder , send your pngs to me on Facebook and I'll add them .
and yeah changing pngs after cloning the repository will work too
